/*!

=========================================================
* Now UI Dashboard PRO React - v1.5.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro-react
* Copyright 2021 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";
import { getNumberOfCreators, getProfiles } from "assets/web3/web3";

// reactstrap components
import {
  Card,
  CardBody,
  Row,
  Col,
} from "reactstrap";

// core components
import PanelHeader from "components/PanelHeader/PanelHeader.js";

import { IPFS_URL } from "assets/js/constants";

function Dashboard() {
  
  const [creators, setCreators] = React.useState(0);
  const [profiles, setProfiles] = React.useState([]);
  
  React.useEffect(() => {
    async function getInfo(){
      const info = await getNumberOfCreators();
      setCreators(info);
      const profilesArray = await getProfiles();
      setProfiles(profilesArray);
    }
    getInfo();
  }, [])

  return (
    <>
      <PanelHeader
        size="sm"
        
      />
      <div className="content">
        <Row>
          <Col xs={12} md="12">
            <Card className="card-stats card-raised">
              <CardBody>
                <Row>
                  <Col md="4">
                    <div className="statistics">
                      <div className="info">
                        <div className="icon icon-primary">
                          <i className="now-ui-icons ui-2_chat-round" />
                        </div>
                        <h3 className="info-title">0</h3>
                        <h6 className="stats-title">Posts Created</h6>
                      </div>
                    </div>
                  </Col>
                  <Col md="4">
                    <div className="statistics">
                      <div className="info">
                        <div className="icon icon-success">
                          <i className="now-ui-icons business_money-coins" />
                        </div>
                        <h3 className="info-title">
                          <small>$</small>
                          0
                        </h3>
                        <h6 className="stats-title">Revenue Generated by Users</h6>
                      </div>
                    </div>
                  </Col>
                  <Col md="4">
                    <div className="statistics">
                      <div className="info">
                        <div className="icon icon-info">
                          <i className="now-ui-icons users_single-02" />
                        </div>
                        <h3 className="info-title">{creators ? creators : 0}</h3>
                        <h6 className="stats-title">Creators</h6>
                      </div>
                    </div>
                  </Col>
                  
                </Row>
              </CardBody>
            </Card>

            <h3>Profiles:</h3>
            <Card className="card-stats card-raised">
                <CardBody>
                  {profiles && profiles.length > 0 ?
                    <Row>
                      {profiles.map(profile => 
                          
                          <Col key={profile.profile} xs={6} className="space-top">
                            <Row>
                              <Col xs={3}>
                                <img src={`${IPFS_URL}/${profile.avatar}`} style={{width:200}} alt="Profile" />
                              </Col>
                              <Col xs={4}>
                                <p className="bold">
                                  {profile.profile.toUpperCase()}
                                </p>
                                <p>{profile.metadata.about}</p>
                                <p>{profile.metadata.activity}</p>
                              </Col>
                            </Row>
                            
                            
                          </Col>
                           
                      )}
                    </Row> : <></>
                  }
                </CardBody>
            </Card>
            
          </Col>
        </Row>
      </div>
    </>
  );
}

export default Dashboard;
