/*!

=========================================================
* Now UI Dashboard PRO React - v1.5.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro-react
* Copyright 2021 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";
import { getNumberOfCreators, getProfiles } from "assets/web3/web3";

// reactstrap components
import {
  Card,
  CardBody,
  Row,
  Col,
  Button
} from "reactstrap";

// core components
import PanelHeader from "components/PanelHeader/PanelHeader.js";

import { IPFS_URL } from "assets/js/constants";

function Dashboard() {
  
  const [creators, setCreators] = React.useState(0);
  const [profiles, setProfiles] = React.useState([]);
  
  React.useEffect(() => {
    async function getInfo(){
      const info = await getNumberOfCreators();
      setCreators(info);
      const profilesArray = await getProfiles();
      setProfiles(profilesArray);
    }
    getInfo();
  }, [])

  return (
    <>
      <PanelHeader
        size="sm"
        
      />
      <div className="content">
        <Row>
          <Col xs={12} md="12">
            <Card className="card-stats card-raised">
              <CardBody>
                <Row>
                  <Col md="4">
                    <div className="statistics">
                      <div className="info">
                        <div className="icon icon-primary">
                          <i className="now-ui-icons ui-2_chat-round" />
                        </div>
                        <h3 className="info-title">6</h3>
                        <h6 className="stats-title">Posts Created</h6>
                      </div>
                    </div>
                  </Col>
                  <Col md="4">
                    <div className="statistics">
                      <div className="info">
                        <div className="icon icon-success">
                          <i className="now-ui-icons business_money-coins" />
                        </div>
                        <h3 className="info-title">
                          <small>$</small>
                          0
                        </h3>
                        <h6 className="stats-title">Revenue Generated by Users</h6>
                      </div>
                    </div>
                  </Col>
                  <Col md="4">
                    <div className="statistics">
                      <div className="info">
                        <div className="icon icon-info">
                          <i className="now-ui-icons users_single-02" />
                        </div>
                        <h3 className="info-title">{creators ? creators : 0}</h3>
                        <h6 className="stats-title">Creators</h6>
                      </div>
                    </div>
                  </Col>
                  
                </Row>
              </CardBody>
            </Card>

            <h3>Profiles:</h3>
            
                  {profiles && profiles.length > 0 ?
                    <Row>
                      {profiles.map((profile, index) => 
                          <Col key={profile.profile} style={{paddingLeft:'20px'}} xs={{span:6, offset:4}} className="space-top pointer" onClick={() => window.location.href=`/admin/profile/${index}`}>
                            <Row>
                              <Col xs={12}>
                                <img src={`${IPFS_URL}/${profile.banner}`} style={{width:500, height:300}} alt="Profile" />
                              </Col>
                              <Col xs={12} lg={2} className="text-center">
                                <img  src={`${IPFS_URL}/${profile.avatar}`} style={{width:100, borderRadius:'50%', marginTop:'-30%'}} alt="Profile" />
                                <p className="bold">
                                  {profile.profile.toUpperCase()}
                                </p>
                                <Button color="warning">Visit Profile</Button>
                              </Col>
                              <Col xs={12} lg={3}>
                                <p style={{whiteSpace:'normal', wordBreak:'break-all'}}>{profile.metadata.activity}</p>
                                <p style={{whiteSpace:'normal', wordBreak:'break-all'}}>{profile.metadata.about}</p>
                                
                              </Col>
                            </Row>
                          </Col>
                           
                      )}
                    </Row> : <></>
                  }
                
          </Col>
        </Row>
      </div>
    </>
  );
}

export default Dashboard;
